# Use root/example as user/password credentials
version: "3.1"

services:   
    api:
        build: .
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        working_dir: /app
